### PR TITLE
Added a blog on SkyWalking Application Monitor

### PR DESCRIPTION
**Pull request by siddhantprateek**

### CODE REVIEW

**Comment by orkhan-huseyn** [comment]
Hey @siddhantprateek, please, update the `date` in heading to match todays date (or whenever you finished the task). 
Also author name should match the file name. In your case, the name is `siddhant-prateek`.

**Comment by siddhantprateek** [comment]
can u tell me which time I should mention on, is it PST or GMT or I should follow my country's time

**Comment by orkhan-huseyn** [comment]
@siddhantprateek I believe this is not important as long as the date is correct :) you can use your local time.

**Comment by orkhan-huseyn** [comment]
@sakows (or @sakomws) we can merge this PR and let @siddhantprateek share his post :)

**Pull request merged**
